version: '2.2'

services:
  postgres:
    container_name: venomdrop_postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: venomdrop_dev
      POSTGRESQL_FSYNC: "off"
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "55432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin:
